apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.destination.repo}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - springboot
    - microservice
    
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ProductManagement
  description: ${{ values.description }}
  links:
    - url: http://localhost:9901/ProductManagement/
      title: ProductManagement Website
      icon: dashboard
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{values.destination.owner}}
  providesApis:
    - ProductManagement
  apiConsumedBy: 
    - OrderManagement
  #consumesApis:
  #  - petstore
  definition:
    $text: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}/blob/master/ProductManagement/ProductManagement/src/main/resources/api-docs.yaml